### ISSUE TITLE
Chinese font support

### ISSUE THREAD

**Issue by Inverstar** [Exodia-OS/exodia-wireless-ISO#3]
Hello, I am a netizen from Chinese mainland. When installing and selecting Chinese, I found that the font could not be displayed normally. Can I preset the Chinese font?thanks very much!

**Comment by mmsaeed509** [comment]
you can install Chinese font from  [here](https://wiki.archlinux.org/title/Localization/Chinese)
also, read this [article](https://wiki.archlinux.org/title/Localization/Simplified_Chinese) from arch wiki

if you installed the new release [**`exodia-home-2023.07.06-x86_64.iso`**](https://drive.google.com/file/d/1d3btoTDUXLGt0Q4dWn2mCPcn15IIrLP3/view?usp=sharing) release, you can use the pre-installed `CahtGPT` for helping you 

you can install it if you use an older release
```bash
install tgpt
```
to use `CahtGPT`
open the terminal
```bash
tgpt "how to install Chinese fonts in archlinux"
```
