### ISSUE TITLE
polybar doesn't work

### ISSUE THREAD

**Issue by harperreynell** [Exodia-OS/exodia-wireless-ISO#4]
I installed exodia os wireless version from official site, but my polybar doesn't work.
I'm new to bspwm and don't know how to fix this.
Will appreciate any help.

**Comment by mmsaeed509** [comment]
update your system

**Comment by 4k4m1m3** [comment]
> I installed exodia os wireless version from official site, but my polybar doesn't work. I'm new to bspwm and don't know how to fix this. Will appreciate any help.

Try to download and install again
