### ISSUE TITLE
Conflicto entre openbsd-netcat y gnu-netcat

### ISSUE THREAD

**Issue by 4k4m1m3** [Exodia-OS/exodia-wireless-ISO#5]
Existe un conflicto en la instalación inicial (Exodia Wireless) entre:

`openbsd-netcat y gnu-netcat `

❯ **remove gnu-netcat**
error: no se pudo preparar la operación (no se pudo satisfacer las dependencias)
:: quitando gnu-netcat se rompe la dependencia con «gnu-netcat», necesaria para el paquete lbd

❯ **remove openbsd-netcat**
error: no se ha encontrado el paquete: openbsd-netcat

❯ **update**
:: Sincronizando las bases de datos de los paquetes...
 no se pudo descargar exodia-repo.db
 no se pudo descargar Exodia-PenTest-Repo.db
 no se pudo descargar exodia-community-repo.db
 core                                                                  129,5 KiB  17,4 KiB/s 00:07 [##########################################################] 100%
 extra                                                                   8,3 MiB   831 KiB/s 00:10 [##########################################################] 100%
 community                                                              45,0   B  6,00   B/s 00:07 [##########################################################] 100%
error: no se pudo obtener el archivo «exodia-repo.db» desde exodia-os.github.io: Resolving timed out after 10000 milliseconds
error: no se pudo obtener el archivo «Exodia-PenTest-Repo.db» desde exodia-os.github.io: Connection time-out
error: no se pudo obtener el archivo «exodia-community-repo.db» desde exodia-os.github.io: Connection time-out
advertencia: demasiados errores al descargar de exodia-os.github.io, pasando al siguiente servidor de la lista
error: no se pudo obtener el archivo «core.db» desde arch.phinau.de: Resolving timed out after 10000 milliseconds
error: no se pudo obtener el archivo «extra.db» desde arch.phinau.de: Connection time-out
error: no se pudo obtener el archivo «community.db» desde arch.phinau.de: Connection time-out
advertencia: demasiados errores al descargar de arch.phinau.de, pasando al siguiente servidor de la lista
error: no se han podido sincronizar todas las bases de datos (error inesperado)

**Comment by Kevinbarrero** [comment]
there is not conflict between the packages, please try:
`sudo pacman-key --populate && yay -Syy archlinux-keyring`
after that, if you wanna install openbsd try `sudo pacman -S openbsd-netcat` the command will say openbsd-netcat and gnu-netcat are in conflict, press y and then enter, and that's all, if you wanna just update the system try `sudo pacman -Syu --overwrite="*"`

**Comment by 4k4m1m3** [comment]
Resuelto ✅
