### ISSUE TITLE
not upgrading in wireless version

### ISSUE THREAD

**Issue by firstatack** [Exodia-OS/exodia-wireless-ISO#6]
I have installed the wireless version but I have a dependency problem when installing some packages.
It tells me that the version I have installed is newer than the one in the repository.
The packages that do not run are due to dependencies on other packages, it always asks me for a newer version than the one installed.
how to resolve , pls

**Comment by mmsaeed509** [comment]
first, update your system

```bash
update
```

then try to install 

```bash
install xfce4
# or install from a specific repo (i.e `extra` )
install extra/xfce4
```
